### ISSUE TITLE
Problema con Handlebars e modale

### ISSUE THREAD

**Issue by Efeex** [Efeex/drinketto#1]
Nelle ultime righe del file index.js, riesco a creare un template Handlebars come modale, facendola aprire al click del bottone "view receips" e mostrando al suo interno come titolo il nome della ricetta. Una volta chiusa però e al click su un nuovo pulsante, viene mostrato sempre lo stesso dato. Ho provato ad utilizzare due funzioni bootstrap come alternativa a svuotare il container ma il problema persiste. @jenkin

**Comment by jenkin** [comment]
Dunque, la linea incriminata è [questa](https://github.com/Efeex/drinketto/blob/ce0e512ff51bb740050764fc0e7acb719f2af686/js/index.js#L65): `beerCard = $(recipeCardTpl(ricette)).appendTo(container)`.

Se ogni volta fai append del contenuto di una modale nel contenitore della modale, ottieni una modale con tanti contenuti, il che non ha molto senso.

Devi invece sostituire il vecchio contenuto del contenitore con il nuovo: `beerCard = container.html(recipeCardTpl(ricette))`.

**Comment by Efeex** [comment]
Perfetto grazie mille
